### ISSUE TITLE
Open handle prevents Jest from exiting

### ISSUE THREAD

**Issue by PatrickHeneise** [nearform/fastify-auth0-verify#40]
Thanks for creating this library! I just added it to my API to verify auth0 tokens and running into an issue with jest:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at new CacheableLookup (node_modules/cacheable-lookup/source/index.js:75:14)
      at Object.<anonymous> (node_modules/fastify-auth0-verify/node_modules/got/dist/source/core/index.js:32:24)
      at Object.<anonymous> (node_modules/fastify-auth0-verify/node_modules/got/dist/source/as-promise/types.js:14:16)
```

Implementation is as described in the readme:

```
app.register(require('fastify-auth0-verify'), {
  domain: auth0.domain,
  audience: auth0.audience,
  secret: auth0.clientSecret
})
```

route:

```
module.exports = function (fastify, opts, next) {
  fastify.route({
    method: 'GET',
    url: '/',
    preValidation: fastify.authenticate,
    schema: {
      query: querySchema,
      response: {
        200: bodySerialization
      }
    },
    handler: async (request, reply) => {})
    next()
}
```

test.js

```
const fastify = require('../../../app')
const { agent } = require('../../auth')

let token
beforeAll(async () => {
  token = await agent()
})
afterAll(() => {
  fastify.close()
})

describe('GET /', () => {
  it('should return', async () => {
    const response = await fastify.inject({
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`
      },
      url: '/'
    })
    expect(response.statusCode).toEqual(200)
  })
})
```

**Comment by salmanm** [comment]
Not sure if it's related, but did you try `fastify.server.unref()`?

**Comment by PatrickHeneise** [comment]
Just added it, but doesn't seem to make a difference, getting the same message.
